### ISSUE TITLE
Ошибка при открытии редактора ПРО

### ISSUE THREAD

**Issue by petypen** [GenVP/TipsInCD3_EDT#11]
При открытии редактора ПРО выводится сообщение об ошибке: "Ошибка загрузки объектов локального контекста: ВнешнийОбъект"

![2023-08-15_20-25-14](https://github.com/GenVP/TipsInCD3_EDT/assets/6500075/f451eee7-a187-471f-99e0-eea0d1938c25)

**Comment by GenVP** [comment]
Спасибо за исправление. Предлагаю исправить попроще.

Заменить:
```
// Объединение общих переменных и переменных обработчика
ПеременныеJSON = Лев(ПеременныеJSON, СтрДлина(ПеременныеJSON) - 1) + "," + Сред(ПеременныеОбработчика, 2);
```
На:
```
Если ПеременныеJSON = "{}" Тогда
	ПеременныеJSON = ПеременныеОбработчика;
Иначе
	// Объединение общих переменных и переменных обработчика
	ПеременныеJSON = Лев(ПеременныеJSON, СтрДлина(ПеременныеJSON) - 1) + "," + Сред(ПеременныеОбработчика, 2);
КонецЕсли;
```

**Comment by ViktorErmakov** [comment]
Не используйте конкатенацию, заиените на стршаблон.

**Comment by petypen** [comment]
@GenVP учел ваши замечания. Коммит добавлен.
